### ISSUE TITLE
Redundant case?

### ISSUE THREAD

**Issue by tomjaguarpaw** [rainbyte/frag#3]
This is a bit odd: https://github.com/rainbyte/frag/blob/66202cf5618b0c6e3ae6266d647027fca6c8bc6b/src/Game.hs#L20

          (case (listToILA $ objs) of
               x -> x)

Isn't that just the same as

    (listToILA objs)

?

**Comment by tomjaguarpaw** [comment]
In fact there are quite a few similar examples.

**Comment by rainbyte** [comment]
I'm not completely sure, but I think that case's are used in this way to force evaluation of those objects.

I'll investigate more about this and comment later.

**Comment by tomjaguarpaw** [comment]
`case` of only a default pattern doesn't force its scrutinee.

**Comment by rainbyte** [comment]
Then I suppose those statements could be erased... I'll try later at night, when I arrive home

**Comment by ysangkok** [comment]
@rainbyte, how did it go? This is very interesting.

**Comment by rainbyte** [comment]
@ysangkok. I have modified those lines, and the app did not show any difference.

I suppose they could be replaced without the "case ... of; x -> x".

**Comment by rainbyte** [comment]
I've just updated the code (see [commit 63cfd92](https://github.com/rainbyte/frag/commit/63cfd9208cbd1257d6672f5ed3cf6f53793a7056)), those ´case .. of´ where replaced.

Also more pieces of code were simplified (mostly by suggestion of hlint)

**Comment by rainbyte** [comment]
I think this issue could be closed.
