### ISSUE TITLE
Include animated GIF in the README

### ISSUE THREAD

**Issue by ivanperez-keera** [rainbyte/frag#4]
This project was always quite impressive for what it achieved.

It would be great to show it by including an animated GIF in the README.

I just checked and it compiles out of the box.

**Comment by ivanperez-keera** [comment]
(Suggestion: tag this issue 'help wanted', 'hacktoberfest', and 'beginner' and you may find some awesome contributor willing to participate and contribute the GIF :) )

**Comment by AdamTheWizard** [comment]
Hey, is this still open? I'm new to all this and would love to try and help out :)

**Comment by ivanperez-keera** [comment]
@rainbyte What do you think? Would you accept such a PR?

**Comment by rainbyte** [comment]
Sorry for late response.

@ivanperez-keera of course I would accept a PR for this.

Please feel free to contribute.

**Comment by ivanperez-keera** [comment]
@rainbyte Thanks!

@AdamTheWizard  I'm giving a talk on Game Programming in Haskell, 4 hours from now. I've included a 15 second GIF built from a youtube video of frag. However, if you can record a higher-resolution GIF for the repo, I'd be happy to use it for the slides too (and credit you accordingly :smiley: )
