### ISSUE TITLE
Install using stack failed

### ISSUE THREAD

**Issue by gustavonmartins** [rainbyte/frag#5]
I tried to install frag today by typing stack install frag, and got the following error:

Configuring frag-1.1.2...
Building frag-1.1.2...
Preprocessing executable 'frag' for frag-1.1.2...

on the commandline: warning:
    The -fvia-C flag does nothing; it will be removed in a future GHC release
[ 1 of 39] Compiling TGA              ( src/TGA.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/frag/frag-tmp/TGA.o )
[ 2 of 39] Compiling Textures         ( src/Textures.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/frag/frag-tmp/Textures.o )

src/Textures.hs:35:19: error:
    Variable not in scope:
      catch
        :: IO (Maybe (Size, PixelData Word8))
           -> (t0 -> IO (Maybe a0)) -> IO (Maybe (Size, PixelData Word8))

**Comment by rainbyte** [comment]
I will test this today at night. Thanks for the report!

**Comment by rainbyte** [comment]
I couldn't reproduce this on my machine with current code.

Could you try making a clean clone of the repo and doing `stack build`?

**Comment by rainbyte** [comment]
Also, which stack version and system are you using?

**Comment by gustavonmartins** [comment]
My system is Ubuntu 17.10 
stack --version yields: **Version 1.1.2 x86_64 hpack-0.14.1**
Doing  a clean clone of the repo and doing stack build works, but when I go to the executable and type ./frag, I get the following error: **frag: user error (unknown GLUT entry glutInit)**

**Comment by turion** [comment]
You probably need to install a Ubuntu package like `haskell-glut` or `freeglut`.

**Comment by rainbyte** [comment]
Maybe that's the case, probably it doesn't happen on my pc because I have freeglut installed.

If installing freeglut solves the problem, I will add a note about it to the readme.

**Comment by namoscagnm** [comment]
Problem solved thanks to turion comment.
I dont have haskell-glut nor freeglut, but I have freeglut3 as install options. After doing sudo apt-get install freeglut3 and doing stack build again on the downloaded file, the game now opens as expected :)
Please, insert the freeglut (3?) need inside the installation instructions.
Thanks

**Comment by gustavonmartins** [comment]
Problem solved thanks to turion comment.
I dont have haskell-glut nor freeglut, but I have freeglut3 as install options. After doing sudo apt-get install freeglut3 and doing stack build again on the downloaded file, the game now opens as expected :)
Please, insert the freeglut (3?) need inside the installation instructions.
I reopened and will close it when this warning is inside the official instructions.
Is it possible to put an automatic check to see if this package is installed while doing stack build?

**Comment by rainbyte** [comment]
This dependency is already stated on the README.
